version: '3.9'

services:
  streamlit:
    image: streamlit-pygwalker:latest
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    deploy:
      resources:
        limits:
          cpus: '8.0'
          memory: 16G
